#!/usr/bin/env bash

TRIMMED_HOME=$(realpath -s "$HOME")
has() { type -p "$1" >/dev/null; }

# Copy all files starting with . to ~
find . -maxdepth 1 -type f -name ".*" -exec cp -uv {} "$TRIMMED_HOME/" \;

#ensure no residual copilot files are copied
if [ -d "$TRIMMED_HOME/.vim/pack/github/start/copilot.vim" ] ; then
    rm -rv "$TRIMMED_HOME/.vim/pack/github/start/copilot.vim"
fi

# Copy only specified directories
cp -ruv "./bin" "$TRIMMED_HOME/"
cp -ruv "./.vim" "$TRIMMED_HOME/"
cp -ruv "./.config" "$TRIMMED_HOME/"

# Ensure Documents folder (used for cloned code) exists
if [ -d "$TRIMMED_HOME/Documents" ] ; then
    mkdir -p "$TRIMMED_HOME/Documents"
fi

# check if neofetch is already cloned
if [ -d "$TRIMMED_HOME/Documents/neofetch" ] ; then
    # if it is, pull latest version
    git -C "$TRIMMED_HOME/Documents/neofetch" pull
else
    # otherwise, clone neofetch from github and place it into ~/Documents/neofetch
    git clone "https://github.com/dylanaraps/neofetch.git/" "$TRIMMED_HOME/Documents/neofetch"
fi

# ensure ~/bin/neofetch symlink exists
if [ ! -f "$TRIMMED_HOME/bin/neofetch" ] ; then
    ln -sv "$TRIMMED_HOME/Documents/neofetch/neofetch" "$TRIMMED_HOME/bin/neofetch"
fi

#Check if rayshud is already cloned
if has "steam" && [ -d "$TRIMMED_HOME/Documents/rayshud" ] ; then
    # if it is, pull latest version
    git -C "$TRIMMED_HOME/Documents/rayshud" pull
elif has "steam" ; then
    git clone "https://github.com/raysfire/rayshud.git" "$TRIMMED_HOME/Documents/rayshud"
fi

if [ -d "/Applications/Obsidian.app" ] ; then
    # ensure ~/bin/obsidian symlink exists
    if [ ! -f "$TRIMMED_HOME/bin/obsidian" ] ; then
        ln -sv "/Applications/Obsidian.app/Contents/MacOS/Obsidian" "$TRIMMED_HOME/bin/obsidian"
    fi
fi

# source new bashrc
# TODO verify this actually works
. "$TRIMMED_HOME/.bashrc"

# nuke bashrc on termux to avoid double sourcing on startup
if [ -n "$TERMUX_VERSION" ] ; then
    rm -v "$TRIMMED_HOME/.bashrc"
fi
