#!/bin/bash

TRIMMED_HOME=$(realpath -s "$HOME")

# Copy all files starting with . to ~
find . -maxdepth 1 -type f -name ".*" -exec cp -v {} "$TRIMMED_HOME/" \;

# Copy only specified directories
cp -rv "./bin" "$TRIMMED_HOME/"
cp -rv "./.vim" "$TRIMMED_HOME/"
cp -rv "./.config" "$TRIMMED_HOME/"

# Ensure Documents folder (used for cloned code) exists
if [ -d "$TRIMMED_HOME/Documents" ] ; then
    mkdir -p "$TRIMMED_HOME/Documents"
fi

# check if neofetch is already cloned
if [ -d "$TRIMMED_HOME/Documents/neofetch" ] ; then
    # if it is, pull latest version
    git -C "$TRIMMED_HOME/Documents/neofetch" pull
else
    # otherwise, clone neofetch from github and place it into ~/Documents/neofetch
    git clone "https://github.com/dylanaraps/neofetch.git/" "$TRIMMED_HOME/Documents/neofetch"
fi

# ensure ~/bin/neofetch symlink exists
if [ ! -f "$TRIMMED_HOME/bin/neofetch" ] ; then
    ln -sv "$TRIMMED_HOME/Documents/neofetch/neofetch" "$TRIMMED_HOME/bin/neofetch"
fi

# check if ytfzf is already cloned
if [ -d "$TRIMMED_HOME/Documents/ytfzf" ] ; then
    # if it is, pull latest version
    git -C "$TRIMMED_HOME/Documents/ytfzf" pull
else
    # otherwise, clone ytfzf from github and place it into ~/Documents/ytfzf
    git clone "https://github.com/pystardust/ytfzf.git/" "$TRIMMED_HOME/Documents/ytfzf"
fi

# ensure ~/bin/ytfzf symlink exists
if [ ! -f "$TRIMMED_HOME/bin/ytfzf" ] ; then
    ln -sv "$TRIMMED_HOME/Documents/ytfzf/ytfzf" "$TRIMMED_HOME/bin/ytfzf"
fi

# check if zspotify is already cloned
if [ -d "$TRIMMED_HOME/Documents/zspotify" ] ; then
    # if it is, pull latest version
    git -C "$TRIMMED_HOME/Documents/zspotify" pull
else
    # otherwise, clone zspotify from github and place it into ~/Documents/zspotify
    git clone "https://github.com/THIS-IS-NOT-A-BACKUP/zspotify" "$TRIMMED_HOME/Documents/zspotify"
fi

# ensure ~/bin/zspotify alias exists
if [ ! -f "$TRIMMED_HOME/bin/zspotify" ] ; then
    echo '#!/bin/bash
python3 "$TRIMMED_HOME/Documents/zspotify/zspotify/__main__.py" "$@"' > "$TRIMMED_HOME/bin/zspotify";
    chmod +x "$TRIMMED_HOME/bin/zspotify"
fi

# source new bashrc
# TODO verify this actually works
. "$TRIMMED_HOME/.bashrc"
