[backdrop]
blur_intensity = 0.14999999664723873
enabled = true
tint_intensity = 0.0

[bar.default]
background_opacity = 0.0
capsule = true
center = [ "active_window" ]
concave_edge_corners = false
end = [ "group:g1" ]
margin_ends = 0
padding = 10
start = [ "session", "launcher", "wallpaper", "workspaces", "media", "tray" ]

    [bar.default.dead_zone.actions]
    left = "panel-toggle control-center home"

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "notifications", "volume", "network", "bluetooth", "cpu", "ram", "battery", "date", "clock" ]
    opacity = 1.0
    padding = 6.0

[brightness]
enable_ddcutil = true

[calendar]
enabled = true

    [calendar.account.personal_google]
    type = "google"

[desktop_widgets]
enabled = false

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 854.0
    cy = 885.0
    output = "eDP-1"
    placement_height = 1067.0
    placement_width = 1707.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[osd]
border = false
offset_y = 168
position = "bottom_center"

    [osd.kinds]
    lock_keys = false

[shell]
font_family = "DejaVu Sans"
screen_time_enabled = true

    [shell.animation]
    speed = 3.0000000447034836

[theme]
builtin = "Nord"
source = "wallpaper"

[wallpaper]
directory = "/home/fritz/.config/niri"

    [wallpaper.default]
    path = "/home/fritz/.config/niri/Background.jpg"

    [wallpaper.last]
    path = "/home/fritz/.config/niri/Background.jpg"

[weather]
unit = "imperial"

[widget.active_window]
title_scroll = "on_hover"

[widget.clock]
format = "{:%I:%M:%S %p}"

[widget.cpu]
glyph = "cpu"
visualization = "none"

[widget.date]
format = "{:%m/%d/%y}"

[widget.launcher]
enabled = false

[widget.media]
hide_when_no_media = true

[widget.notifications]
enabled = false

[widget.ram]
glyph = "stack-front"
stat = "ram_pct"
visualization = "none"

[widget.wallpaper]
enabled = false
